  nmw:
    url: "https://cdn.gh-proxy.org/https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.meta.yml"
    download_path: "whoisyourdaddy/downloads/nmw"
    ori_config_name: "ori_proxy.yaml"
    tar_topkey: proxies
    only_proxy_file: "only_proxy.yaml"    
    override_file: [override-set.yaml, override-gp-rules.yaml]
    f_config_path: "whoisyourdaddy/subs"
    f_config_name: "nmw.yaml"

  cm:
    url: "https://c1m3p2a8g2e6s.lancelot.dpdns.org/sub?token=c241a812d6b3518cb12992c67d9efafd&clash"
    download_path: "whoisyourdaddy/downloads/cm"
    ori_config_name: "ori_proxy.yaml"
    tar_topkey: proxies
    only_proxy_file: "only_proxy.yaml"    
    override_file: [override-set.yaml, override-gp-rules.yaml]
    f_config_path: "whoisyourdaddy/subs"
    f_config_name: "cm.yaml"

  kulao:
    url: "https://cdn.gh-proxy.org/https://raw.githubusercontent.com/Jsnzkpg/Jsnzkpg/Jsnzkpg/Jsnzkpg"
    download_path: "whoisyourdaddy/downloads/kulao"
    ori_config_name: "ori_proxy.yaml"
    tar_topkey: proxies
    only_proxy_file: "only_proxy.yaml"    
    override_file: [override-set.yaml, override-gp-rules.yaml]
    f_config_path: "whoisyourdaddy/subs"
    f_config_name: "kulao.yaml"

  ygkkk:
    url: "https://y3g2k1k5k.lancelot.dpdns.org/0148c0dc-8d10-4655-9242-e888f0a373af/pcl"
    download_path: "whoisyourdaddy/downloads/ygkkk"
    ori_config_name: "ori_proxy.yaml"
    tar_topkey: proxies
    only_proxy_file: "only_proxy.yaml"    
    override_file: [override-set.yaml, override-gp-rules.yaml]
    f_config_path: "whoisyourdaddy/subs"
    f_config_name: "ygkkk.yaml"

  fx:
    url: "https://sub.9999669.xyz/sub?id=rs1&target=clash"
    download_path: "whoisyourdaddy/downloads/fx"
    ori_config_name: "ori_proxy.yaml"
    tar_topkey: proxies
    only_proxy_file: "only_proxy.yaml"    
    override_file: [override-set.yaml, override-gp-rules.yaml]
    f_config_path: "whoisyourdaddy/subs"
    f_config_name: "fx.yaml"
  
  joey:
    url: "https://c4f2n5e3w7p5a6g7e5s.lancelot.dpdns.org/admin/sub?target=clash"
    download_path: "whoisyourdaddy/downloads/joey"
    ori_config_name: "ori_proxy.yaml"
    tar_topkey: proxies
    only_proxy_file: "only_proxy.yaml"    
    override_file: [override-set.yaml, override-gp-rules.yaml]
    f_config_path: "whoisyourdaddy/subs"
    f_config_name: "joey.yaml"
