mysubs:
  bpb:
    url: "https://bpb.lancelot.dpdns.org/sub/normal/0%3A5nx.X*%3BF3pv%40lq?app=clash#%F0%9F%92%A6%20BPB%20Normal"
    download_path: "whoisyourdaddy/downloads/bpb"
    ori_config_name: "ori_proxy.yaml"
    tar_topkey: proxies
    only_proxy_file: "only_proxy.yaml"    
    override_file: [override-set.yaml, override-gp-rules.yaml]
    f_config_path: "whoisyourdaddy/subs"
    f_config_name: "bpb.yaml"

  nmw:
    url: "https://cdn.gh-proxy.org/https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.meta.yml"
    download_path: "whoisyourdaddy/downloads/nmw"
    ori_config_name: "ori_proxy.yaml"
    tar_topkey: proxies
    only_proxy_file: "only_proxy.yaml"    
    override_file: [override-set.yaml, override-gp-rules.yaml]
    f_config_path: "whoisyourdaddy/subs"
    f_config_name: "nmw.yaml"

  cm:
    url: "https://c1m2p9a3g2e8s.lancelot.dpdns.org/sub?token=985c3612137ea5b21ac75661f044d11a&clash"
    download_path: "whoisyourdaddy/downloads/cm"
    ori_config_name: "ori_proxy.yaml"
    tar_topkey: proxies
    only_proxy_file: "only_proxy.yaml"    
    override_file: [override-set.yaml, override-gp-rules.yaml]
    f_config_path: "whoisyourdaddy/subs"
    f_config_name: "cm.yaml"

  kulao:
    url: "https://cdn.gh-proxy.org/https://raw.githubusercontent.com/Jsnzkpg/Jsnzkpg/Jsnzkpg/Jsnzkpg"
    download_path: "whoisyourdaddy/downloads/kulao"
    ori_config_name: "ori_proxy.yaml"
    tar_topkey: proxies
    only_proxy_file: "only_proxy.yaml"    
    override_file: [override-set.yaml, override-gp-rules.yaml]
    f_config_path: "whoisyourdaddy/subs"
    f_config_name: "kulao.yaml"

  ygkkk:
    url: "https://y1g6y4g8.lancelot.dpdns.org/6a36a3cb-b683-43db-990c-e5c6d3e7170c/pcl"
    download_path: "whoisyourdaddy/downloads/ygkkk"
    ori_config_name: "ori_proxy.yaml"
    tar_topkey: proxies
    only_proxy_file: "only_proxy.yaml"    
    override_file: [override-set.yaml, override-gp-rules.yaml]
    f_config_path: "whoisyourdaddy/subs"
    f_config_name: "ygkkk.yaml"

  fx:
    url: "https://sub.9999669.xyz/sub?id=rs1&target=clash"
    download_path: "whoisyourdaddy/downloads/fx"
    ori_config_name: "ori_proxy.yaml"
    tar_topkey: proxies
    only_proxy_file: "only_proxy.yaml"    
    override_file: [override-set.yaml, override-gp-rules.yaml]
    f_config_path: "whoisyourdaddy/subs"
    f_config_name: "fx.yaml"

  agg:
    url: "https://cdn.gh-proxy.org/https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity.yml"
    download_path: "whoisyourdaddy/downloads/agg"
    ori_config_name: "ori_proxy.yaml"
    tar_topkey: proxies
    only_proxy_file: "only_proxy.yaml"    
    override_file: [override-set.yaml, override-gp-rules.yaml]
    f_config_path: "whoisyourdaddy/subs"
    f_config_name: "agg.yaml"