name: suboverrider

on:
  workflow_dispatch:
  schedule:
    - cron: '5 */3 * * *'  
  push:
    branches:
      - devdev
      - main
    paths:
      - 'hello_world/**'
      - '.github/workflows/**'

permissions:
  contents: write

jobs:
  suboverrider:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      TZ: Asia/Shanghai
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          ref: devdev
          persist-credentials: true

      - name: run script
        run: |
          chmod +x ./hello_world/run_it.sh
          chmod +x ./hello_world/suboverrider.sh
          ./hello_world/run_it.sh

      - name: pust to reporsitory
        run: |
          git config --local user.email "hello_world@163.com"
          git config --local user.name "hello_world"
          git add whoisyourdaddy/subs
          if git diff --staged --quiet; then
            echo "No updates,skip to push."
          else
            git commit -m "updated:($(date +'%Y-%m-%d %H:%M:%S'))"
            git push origin devdev
          fi
          